## SF Salaries Exercise

In [1]:
import pandas as pd

**Q1. Read Salaries.csv as a dataframe called sal.**

In [28]:
sal=pd.read_csv("Salaries.csv")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_12540\845558534.py:1: DtypeWarning: Columns (0: BasePay, 1: OvertimePay, 2: OtherPay, 3: Benefits, 4: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  sal=pd.read_csv("Salaries.csv")

**Q2. Check the head of the DataFrame.**

In [16]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**Q3. Use the  .info() method to find out how many entries there are.**

In [17]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(3), int64(2), object(4), str(4)
memory usage: 14.7+ MB

**Q4. What is the average BasePay?**

In [23]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')
sal['BasePay'].mean()

np.float64(66325.44884048769)

**Q5. What is the highest amount of OvertimePay in the data set?**

In [26]:
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors='coerce')
sal['OvertimePay'].max()

np.float64(245131.88)

**Q6. What is the Title of JOSHEPH DRISCOLL? Note:Use all Caps, otherwise you may get an answer that does'nt match up(there is also a lowercase Joseph Driscoll).**

In [35]:
sal[sal['EmployeeName']=='JOSHEPH DRISCOLL']

Empty DataFrame
Columns: [Id, EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year, Notes, Agency, Status]
Index: []

**Q7. How much does JOSHEPH DRISCOLL make (including benifits)?**

**Q8. What is the name of highest paid person (including benifits)?**

**Q9. What is the name of lowest paid persion(including benifits)? Do you notice something strange about how much he/she is paid?**

**Q10. What was the average (mean) BasePay of all employees per year?(2011-2014)**

**Q11. How many unique job title are there?**

**Q12. What are the top 5 most common job?**

**Q13. How many Job Titles were represented by only one person in 2013?(e.g-Job Titles with only are occurance in 2013?**

**Q14. How many people have the word cheif in their job Title?(This is pretty tricky)**

**Bonus: Is there a correlation between length of the Job Title string \& Salary?**